#!/bin/bash
if [ -z "$1" ]; then
   echo "Deploying TMOS VE WAF playbook tasks"    
   ansible-playbook -K site.yml
else
    if [ "$1" == "ltm" ]; then
       echo "Deploying TMOS VE LTM playbook tasks"
       ansible-playbook -K -e '{ "guest_type": "ltm", "guest_disk_image_size": 13 }' site.yml
   elif [ "$1" == "all" ]; then
       echo "Deploying TMOS VE WAF playbook tasks"
       ansible-playbook -K -e '{ "guest_type": "all", "guest_disk_image_size": 62 }' site.yml
   fi
fi